//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap")]
    public interface XL_DICH_VU_ASMXSoap {
        
        // CODEGEN: Generating message contract since element name Doc_Du_lieuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Doc_Du_lieu", ReplyAction="*")]
        Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.Doc_Du_lieuResponse Doc_Du_lieu(Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.Doc_Du_lieuRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Doc_Du_lieuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Doc_Du_lieu", Namespace="http://tempuri.org/", Order=0)]
        public Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.Doc_Du_lieuRequestBody Body;
        
        public Doc_Du_lieuRequest() {
        }
        
        public Doc_Du_lieuRequest(Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.Doc_Du_lieuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Doc_Du_lieuRequestBody {
        
        public Doc_Du_lieuRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Doc_Du_lieuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Doc_Du_lieuResponse", Namespace="http://tempuri.org/", Order=0)]
        public Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.Doc_Du_lieuResponseBody Body;
        
        public Doc_Du_lieuResponse() {
        }
        
        public Doc_Du_lieuResponse(Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.Doc_Du_lieuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Doc_Du_lieuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Doc_Du_lieuResult;
        
        public Doc_Du_lieuResponseBody() {
        }
        
        public Doc_Du_lieuResponseBody(string Doc_Du_lieuResult) {
            this.Doc_Du_lieuResult = Doc_Du_lieuResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XL_DICH_VU_ASMXSoapChannel : Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XL_DICH_VU_ASMXSoapClient : System.ServiceModel.ClientBase<Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap>, Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap {
        
        public XL_DICH_VU_ASMXSoapClient() {
        }
        
        public XL_DICH_VU_ASMXSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XL_DICH_VU_ASMXSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XL_DICH_VU_ASMXSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XL_DICH_VU_ASMXSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.Doc_Du_lieuResponse Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Doc_Du_lieu(Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.Doc_Du_lieuRequest request) {
            return base.Channel.Doc_Du_lieu(request);
        }
        
        public string Doc_Du_lieu() {
            Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.Doc_Du_lieuRequest inValue = new Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.Doc_Du_lieuRequest();
            inValue.Body = new Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.Doc_Du_lieuRequestBody();
            Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.Doc_Du_lieuResponse retVal = ((Doc_Du_lieu_co_Cau_truc_Internet.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap)(this)).Doc_Du_lieu(inValue);
            return retVal.Body.Doc_Du_lieuResult;
        }
    }
}
