//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCN_Tra_cuu.DV_PET {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DV_PET.XL_DICH_VU_QLNV_1Soap")]
    public interface XL_DICH_VU_QLNV_1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thu_nghiem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Thu_nghiem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thu_nghiem", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Thu_nghiemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLCT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Dang_nhap_QLCT(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLCT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Dang_nhap_QLCTAsync(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLCN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Dang_nhap_QLCN(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLCN", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Dang_nhap_QLCNAsync(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLDV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Dang_nhap_QLDV(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLDV", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Dang_nhap_QLDVAsync(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_NV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Dang_nhap_NV(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_NV", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Dang_nhap_NVAsync(string Ten_Dang_nhap, string Mat_khau);
        
        // CODEGEN: Parameter 'Doc_Nhi_phan_HinhResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Doc_Nhi_phan_Hinh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhResponse Doc_Nhi_phan_Hinh(QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Doc_Nhi_phan_Hinh", ReplyAction="*")]
        System.Threading.Tasks.Task<QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhResponse> Doc_Nhi_phan_HinhAsync(QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLCT_XDO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Dang_nhap_QLCT_XDO(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLCT_XDO", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Dang_nhap_QLCT_XDOAsync(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLCN_XDO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Dang_nhap_QLCN_XDO(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLCN_XDO", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Dang_nhap_QLCN_XDOAsync(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLDV_XDO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Dang_nhap_QLDV_XDO(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLDV_XDO", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Dang_nhap_QLDV_XDOAsync(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_NV_XDO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Dang_nhap_NV_XDO(string Ten_Dang_nhap, string Mat_khau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_NV_XDO", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Dang_nhap_NV_XDOAsync(string Ten_Dang_nhap, string Mat_khau);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Doc_Nhi_phan_Hinh", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Doc_Nhi_phan_HinhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Ma_so;
        
        public Doc_Nhi_phan_HinhRequest() {
        }
        
        public Doc_Nhi_phan_HinhRequest(string Ma_so) {
            this.Ma_so = Ma_so;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Doc_Nhi_phan_HinhResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Doc_Nhi_phan_HinhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Doc_Nhi_phan_HinhResult;
        
        public Doc_Nhi_phan_HinhResponse() {
        }
        
        public Doc_Nhi_phan_HinhResponse(byte[] Doc_Nhi_phan_HinhResult) {
            this.Doc_Nhi_phan_HinhResult = Doc_Nhi_phan_HinhResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XL_DICH_VU_QLNV_1SoapChannel : QLCN_Tra_cuu.DV_PET.XL_DICH_VU_QLNV_1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XL_DICH_VU_QLNV_1SoapClient : System.ServiceModel.ClientBase<QLCN_Tra_cuu.DV_PET.XL_DICH_VU_QLNV_1Soap>, QLCN_Tra_cuu.DV_PET.XL_DICH_VU_QLNV_1Soap {
        
        public XL_DICH_VU_QLNV_1SoapClient() {
        }
        
        public XL_DICH_VU_QLNV_1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XL_DICH_VU_QLNV_1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XL_DICH_VU_QLNV_1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XL_DICH_VU_QLNV_1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Thu_nghiem() {
            return base.Channel.Thu_nghiem();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Thu_nghiemAsync() {
            return base.Channel.Thu_nghiemAsync();
        }
        
        public System.Data.DataSet Dang_nhap_QLCT(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_QLCT(Ten_Dang_nhap, Mat_khau);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Dang_nhap_QLCTAsync(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_QLCTAsync(Ten_Dang_nhap, Mat_khau);
        }
        
        public System.Data.DataSet Dang_nhap_QLCN(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_QLCN(Ten_Dang_nhap, Mat_khau);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Dang_nhap_QLCNAsync(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_QLCNAsync(Ten_Dang_nhap, Mat_khau);
        }
        
        public System.Data.DataSet Dang_nhap_QLDV(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_QLDV(Ten_Dang_nhap, Mat_khau);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Dang_nhap_QLDVAsync(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_QLDVAsync(Ten_Dang_nhap, Mat_khau);
        }
        
        public System.Data.DataSet Dang_nhap_NV(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_NV(Ten_Dang_nhap, Mat_khau);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Dang_nhap_NVAsync(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_NVAsync(Ten_Dang_nhap, Mat_khau);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhResponse QLCN_Tra_cuu.DV_PET.XL_DICH_VU_QLNV_1Soap.Doc_Nhi_phan_Hinh(QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhRequest request) {
            return base.Channel.Doc_Nhi_phan_Hinh(request);
        }
        
        public byte[] Doc_Nhi_phan_Hinh(string Ma_so) {
            QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhRequest inValue = new QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhRequest();
            inValue.Ma_so = Ma_so;
            QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhResponse retVal = ((QLCN_Tra_cuu.DV_PET.XL_DICH_VU_QLNV_1Soap)(this)).Doc_Nhi_phan_Hinh(inValue);
            return retVal.Doc_Nhi_phan_HinhResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhResponse> QLCN_Tra_cuu.DV_PET.XL_DICH_VU_QLNV_1Soap.Doc_Nhi_phan_HinhAsync(QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhRequest request) {
            return base.Channel.Doc_Nhi_phan_HinhAsync(request);
        }
        
        public System.Threading.Tasks.Task<QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhResponse> Doc_Nhi_phan_HinhAsync(string Ma_so) {
            QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhRequest inValue = new QLCN_Tra_cuu.DV_PET.Doc_Nhi_phan_HinhRequest();
            inValue.Ma_so = Ma_so;
            return ((QLCN_Tra_cuu.DV_PET.XL_DICH_VU_QLNV_1Soap)(this)).Doc_Nhi_phan_HinhAsync(inValue);
        }
        
        public string Dang_nhap_QLCT_XDO(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_QLCT_XDO(Ten_Dang_nhap, Mat_khau);
        }
        
        public System.Threading.Tasks.Task<string> Dang_nhap_QLCT_XDOAsync(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_QLCT_XDOAsync(Ten_Dang_nhap, Mat_khau);
        }
        
        public string Dang_nhap_QLCN_XDO(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_QLCN_XDO(Ten_Dang_nhap, Mat_khau);
        }
        
        public System.Threading.Tasks.Task<string> Dang_nhap_QLCN_XDOAsync(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_QLCN_XDOAsync(Ten_Dang_nhap, Mat_khau);
        }
        
        public string Dang_nhap_QLDV_XDO(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_QLDV_XDO(Ten_Dang_nhap, Mat_khau);
        }
        
        public System.Threading.Tasks.Task<string> Dang_nhap_QLDV_XDOAsync(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_QLDV_XDOAsync(Ten_Dang_nhap, Mat_khau);
        }
        
        public string Dang_nhap_NV_XDO(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_NV_XDO(Ten_Dang_nhap, Mat_khau);
        }
        
        public System.Threading.Tasks.Task<string> Dang_nhap_NV_XDOAsync(string Ten_Dang_nhap, string Mat_khau) {
            return base.Channel.Dang_nhap_NV_XDOAsync(Ten_Dang_nhap, Mat_khau);
        }
    }
}
