//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap")]
    public interface XL_DICH_VU_ASMXSoap {
        
        // CODEGEN: Generating message contract since element name Doc_GocResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Doc_Goc", ReplyAction="*")]
        Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocResponse Doc_Goc(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Doc_Goc", ReplyAction="*")]
        System.Threading.Tasks.Task<Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocResponse> Doc_GocAsync(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocRequest request);
        
        // CODEGEN: Generating message contract since element name Ten_Dang_nhap from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLCT", ReplyAction="*")]
        Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTResponse Dang_nhap_QLCT(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dang_nhap_QLCT", ReplyAction="*")]
        System.Threading.Tasks.Task<Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTResponse> Dang_nhap_QLCTAsync(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTRequest request);
        
        // CODEGEN: Generating message contract since element name Chuoi_Tham_so_Khung from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cap_nhat_Ho_so_Cong_ty", ReplyAction="*")]
        Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyResponse Cap_nhat_Ho_so_Cong_ty(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cap_nhat_Ho_so_Cong_ty", ReplyAction="*")]
        System.Threading.Tasks.Task<Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyResponse> Cap_nhat_Ho_so_Cong_tyAsync(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Doc_GocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Doc_Goc", Namespace="http://tempuri.org/", Order=0)]
        public Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocRequestBody Body;
        
        public Doc_GocRequest() {
        }
        
        public Doc_GocRequest(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Doc_GocRequestBody {
        
        public Doc_GocRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Doc_GocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Doc_GocResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocResponseBody Body;
        
        public Doc_GocResponse() {
        }
        
        public Doc_GocResponse(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Doc_GocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Doc_GocResult;
        
        public Doc_GocResponseBody() {
        }
        
        public Doc_GocResponseBody(string Doc_GocResult) {
            this.Doc_GocResult = Doc_GocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Dang_nhap_QLCTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Dang_nhap_QLCT", Namespace="http://tempuri.org/", Order=0)]
        public Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTRequestBody Body;
        
        public Dang_nhap_QLCTRequest() {
        }
        
        public Dang_nhap_QLCTRequest(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Dang_nhap_QLCTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ten_Dang_nhap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mat_khau;
        
        public Dang_nhap_QLCTRequestBody() {
        }
        
        public Dang_nhap_QLCTRequestBody(string Ten_Dang_nhap, string Mat_khau) {
            this.Ten_Dang_nhap = Ten_Dang_nhap;
            this.Mat_khau = Mat_khau;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Dang_nhap_QLCTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Dang_nhap_QLCTResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTResponseBody Body;
        
        public Dang_nhap_QLCTResponse() {
        }
        
        public Dang_nhap_QLCTResponse(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Dang_nhap_QLCTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Dang_nhap_QLCTResult;
        
        public Dang_nhap_QLCTResponseBody() {
        }
        
        public Dang_nhap_QLCTResponseBody(string Dang_nhap_QLCTResult) {
            this.Dang_nhap_QLCTResult = Dang_nhap_QLCTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cap_nhat_Ho_so_Cong_tyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cap_nhat_Ho_so_Cong_ty", Namespace="http://tempuri.org/", Order=0)]
        public Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyRequestBody Body;
        
        public Cap_nhat_Ho_so_Cong_tyRequest() {
        }
        
        public Cap_nhat_Ho_so_Cong_tyRequest(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Cap_nhat_Ho_so_Cong_tyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Chuoi_Tham_so_Khung;
        
        public Cap_nhat_Ho_so_Cong_tyRequestBody() {
        }
        
        public Cap_nhat_Ho_so_Cong_tyRequestBody(string Chuoi_Tham_so_Khung) {
            this.Chuoi_Tham_so_Khung = Chuoi_Tham_so_Khung;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cap_nhat_Ho_so_Cong_tyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cap_nhat_Ho_so_Cong_tyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyResponseBody Body;
        
        public Cap_nhat_Ho_so_Cong_tyResponse() {
        }
        
        public Cap_nhat_Ho_so_Cong_tyResponse(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Cap_nhat_Ho_so_Cong_tyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cap_nhat_Ho_so_Cong_tyResult;
        
        public Cap_nhat_Ho_so_Cong_tyResponseBody() {
        }
        
        public Cap_nhat_Ho_so_Cong_tyResponseBody(string Cap_nhat_Ho_so_Cong_tyResult) {
            this.Cap_nhat_Ho_so_Cong_tyResult = Cap_nhat_Ho_so_Cong_tyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XL_DICH_VU_ASMXSoapChannel : Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XL_DICH_VU_ASMXSoapClient : System.ServiceModel.ClientBase<Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap>, Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap {
        
        public XL_DICH_VU_ASMXSoapClient() {
        }
        
        public XL_DICH_VU_ASMXSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XL_DICH_VU_ASMXSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XL_DICH_VU_ASMXSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XL_DICH_VU_ASMXSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocResponse Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Doc_Goc(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocRequest request) {
            return base.Channel.Doc_Goc(request);
        }
        
        public string Doc_Goc() {
            Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocRequest inValue = new Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocRequest();
            inValue.Body = new Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocRequestBody();
            Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocResponse retVal = ((Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap)(this)).Doc_Goc(inValue);
            return retVal.Body.Doc_GocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocResponse> Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Doc_GocAsync(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocRequest request) {
            return base.Channel.Doc_GocAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocResponse> Doc_GocAsync() {
            Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocRequest inValue = new Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocRequest();
            inValue.Body = new Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Doc_GocRequestBody();
            return ((Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap)(this)).Doc_GocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTResponse Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Dang_nhap_QLCT(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTRequest request) {
            return base.Channel.Dang_nhap_QLCT(request);
        }
        
        public string Dang_nhap_QLCT(string Ten_Dang_nhap, string Mat_khau) {
            Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTRequest inValue = new Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTRequest();
            inValue.Body = new Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTRequestBody();
            inValue.Body.Ten_Dang_nhap = Ten_Dang_nhap;
            inValue.Body.Mat_khau = Mat_khau;
            Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTResponse retVal = ((Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap)(this)).Dang_nhap_QLCT(inValue);
            return retVal.Body.Dang_nhap_QLCTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTResponse> Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Dang_nhap_QLCTAsync(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTRequest request) {
            return base.Channel.Dang_nhap_QLCTAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTResponse> Dang_nhap_QLCTAsync(string Ten_Dang_nhap, string Mat_khau) {
            Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTRequest inValue = new Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTRequest();
            inValue.Body = new Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Dang_nhap_QLCTRequestBody();
            inValue.Body.Ten_Dang_nhap = Ten_Dang_nhap;
            inValue.Body.Mat_khau = Mat_khau;
            return ((Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap)(this)).Dang_nhap_QLCTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyResponse Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Cap_nhat_Ho_so_Cong_ty(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyRequest request) {
            return base.Channel.Cap_nhat_Ho_so_Cong_ty(request);
        }
        
        public string Cap_nhat_Ho_so_Cong_ty(string Chuoi_Tham_so_Khung) {
            Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyRequest inValue = new Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyRequest();
            inValue.Body = new Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyRequestBody();
            inValue.Body.Chuoi_Tham_so_Khung = Chuoi_Tham_so_Khung;
            Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyResponse retVal = ((Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap)(this)).Cap_nhat_Ho_so_Cong_ty(inValue);
            return retVal.Body.Cap_nhat_Ho_so_Cong_tyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyResponse> Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Cap_nhat_Ho_so_Cong_tyAsync(Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyRequest request) {
            return base.Channel.Cap_nhat_Ho_so_Cong_tyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyResponse> Cap_nhat_Ho_so_Cong_tyAsync(string Chuoi_Tham_so_Khung) {
            Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyRequest inValue = new Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyRequest();
            inValue.Body = new Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.Cap_nhat_Ho_so_Cong_tyRequestBody();
            inValue.Body.Chuoi_Tham_so_Khung = Chuoi_Tham_so_Khung;
            return ((Ung_dung_Quan_ly_Cong_ty_DeskTop.DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap)(this)).Cap_nhat_Ho_so_Cong_tyAsync(inValue);
        }
    }
}
