//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FORM_DO_AN.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.XL_DICH_VU_ASMXSoap")]
    public interface XL_DICH_VU_ASMXSoap {
        
        // CODEGEN: Generating message contract since element name docDuLieuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/docDuLieu", ReplyAction="*")]
        FORM_DO_AN.ServiceReference1.docDuLieuResponse docDuLieu(FORM_DO_AN.ServiceReference1.docDuLieuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/docDuLieu", ReplyAction="*")]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.docDuLieuResponse> docDuLieuAsync(FORM_DO_AN.ServiceReference1.docDuLieuRequest request);
        
        // CODEGEN: Generating message contract since element name tenBang from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/docBang", ReplyAction="*")]
        FORM_DO_AN.ServiceReference1.docBangResponse docBang(FORM_DO_AN.ServiceReference1.docBangRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/docBang", ReplyAction="*")]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.docBangResponse> docBangAsync(FORM_DO_AN.ServiceReference1.docBangRequest request);
        
        // CODEGEN: Generating message contract since element name chuoiXml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/themDuLieu", ReplyAction="*")]
        FORM_DO_AN.ServiceReference1.themDuLieuResponse themDuLieu(FORM_DO_AN.ServiceReference1.themDuLieuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/themDuLieu", ReplyAction="*")]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.themDuLieuResponse> themDuLieuAsync(FORM_DO_AN.ServiceReference1.themDuLieuRequest request);
        
        // CODEGEN: Generating message contract since element name Chuoi_Xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cap_nhat", ReplyAction="*")]
        FORM_DO_AN.ServiceReference1.Cap_nhatResponse Cap_nhat(FORM_DO_AN.ServiceReference1.Cap_nhatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cap_nhat", ReplyAction="*")]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.Cap_nhatResponse> Cap_nhatAsync(FORM_DO_AN.ServiceReference1.Cap_nhatRequest request);
        
        // CODEGEN: Generating message contract since element name Chuoi_Xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Xoa", ReplyAction="*")]
        FORM_DO_AN.ServiceReference1.XoaResponse Xoa(FORM_DO_AN.ServiceReference1.XoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Xoa", ReplyAction="*")]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.XoaResponse> XoaAsync(FORM_DO_AN.ServiceReference1.XoaRequest request);
        
        // CODEGEN: Generating message contract since element name Ma_so from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Doc_Hinh", ReplyAction="*")]
        FORM_DO_AN.ServiceReference1.Doc_HinhResponse Doc_Hinh(FORM_DO_AN.ServiceReference1.Doc_HinhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Doc_Hinh", ReplyAction="*")]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.Doc_HinhResponse> Doc_HinhAsync(FORM_DO_AN.ServiceReference1.Doc_HinhRequest request);
        
        // CODEGEN: Generating message contract since element name Ma_so from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ghi_Hinh", ReplyAction="*")]
        FORM_DO_AN.ServiceReference1.Ghi_HinhResponse Ghi_Hinh(FORM_DO_AN.ServiceReference1.Ghi_HinhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ghi_Hinh", ReplyAction="*")]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.Ghi_HinhResponse> Ghi_HinhAsync(FORM_DO_AN.ServiceReference1.Ghi_HinhRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class docDuLieuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="docDuLieu", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.docDuLieuRequestBody Body;
        
        public docDuLieuRequest() {
        }
        
        public docDuLieuRequest(FORM_DO_AN.ServiceReference1.docDuLieuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class docDuLieuRequestBody {
        
        public docDuLieuRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class docDuLieuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="docDuLieuResponse", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.docDuLieuResponseBody Body;
        
        public docDuLieuResponse() {
        }
        
        public docDuLieuResponse(FORM_DO_AN.ServiceReference1.docDuLieuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class docDuLieuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docDuLieuResult;
        
        public docDuLieuResponseBody() {
        }
        
        public docDuLieuResponseBody(string docDuLieuResult) {
            this.docDuLieuResult = docDuLieuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class docBangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="docBang", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.docBangRequestBody Body;
        
        public docBangRequest() {
        }
        
        public docBangRequest(FORM_DO_AN.ServiceReference1.docBangRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class docBangRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tenBang;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cot;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dieuKien;
        
        public docBangRequestBody() {
        }
        
        public docBangRequestBody(string tenBang, string cot, string dieuKien) {
            this.tenBang = tenBang;
            this.cot = cot;
            this.dieuKien = dieuKien;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class docBangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="docBangResponse", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.docBangResponseBody Body;
        
        public docBangResponse() {
        }
        
        public docBangResponse(FORM_DO_AN.ServiceReference1.docBangResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class docBangResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docBangResult;
        
        public docBangResponseBody() {
        }
        
        public docBangResponseBody(string docBangResult) {
            this.docBangResult = docBangResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class themDuLieuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="themDuLieu", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.themDuLieuRequestBody Body;
        
        public themDuLieuRequest() {
        }
        
        public themDuLieuRequest(FORM_DO_AN.ServiceReference1.themDuLieuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class themDuLieuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string chuoiXml;
        
        public themDuLieuRequestBody() {
        }
        
        public themDuLieuRequestBody(string chuoiXml) {
            this.chuoiXml = chuoiXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class themDuLieuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="themDuLieuResponse", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.themDuLieuResponseBody Body;
        
        public themDuLieuResponse() {
        }
        
        public themDuLieuResponse(FORM_DO_AN.ServiceReference1.themDuLieuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class themDuLieuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string themDuLieuResult;
        
        public themDuLieuResponseBody() {
        }
        
        public themDuLieuResponseBody(string themDuLieuResult) {
            this.themDuLieuResult = themDuLieuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cap_nhatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cap_nhat", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.Cap_nhatRequestBody Body;
        
        public Cap_nhatRequest() {
        }
        
        public Cap_nhatRequest(FORM_DO_AN.ServiceReference1.Cap_nhatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Cap_nhatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Chuoi_Xml;
        
        public Cap_nhatRequestBody() {
        }
        
        public Cap_nhatRequestBody(string Chuoi_Xml) {
            this.Chuoi_Xml = Chuoi_Xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Cap_nhatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cap_nhatResponse", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.Cap_nhatResponseBody Body;
        
        public Cap_nhatResponse() {
        }
        
        public Cap_nhatResponse(FORM_DO_AN.ServiceReference1.Cap_nhatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Cap_nhatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cap_nhatResult;
        
        public Cap_nhatResponseBody() {
        }
        
        public Cap_nhatResponseBody(string Cap_nhatResult) {
            this.Cap_nhatResult = Cap_nhatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Xoa", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.XoaRequestBody Body;
        
        public XoaRequest() {
        }
        
        public XoaRequest(FORM_DO_AN.ServiceReference1.XoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XoaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Chuoi_Xml;
        
        public XoaRequestBody() {
        }
        
        public XoaRequestBody(string Chuoi_Xml) {
            this.Chuoi_Xml = Chuoi_Xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.XoaResponseBody Body;
        
        public XoaResponse() {
        }
        
        public XoaResponse(FORM_DO_AN.ServiceReference1.XoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XoaResult;
        
        public XoaResponseBody() {
        }
        
        public XoaResponseBody(string XoaResult) {
            this.XoaResult = XoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Doc_HinhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Doc_Hinh", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.Doc_HinhRequestBody Body;
        
        public Doc_HinhRequest() {
        }
        
        public Doc_HinhRequest(FORM_DO_AN.ServiceReference1.Doc_HinhRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Doc_HinhRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ma_so;
        
        public Doc_HinhRequestBody() {
        }
        
        public Doc_HinhRequestBody(string Ma_so) {
            this.Ma_so = Ma_so;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Doc_HinhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Doc_HinhResponse", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.Doc_HinhResponseBody Body;
        
        public Doc_HinhResponse() {
        }
        
        public Doc_HinhResponse(FORM_DO_AN.ServiceReference1.Doc_HinhResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Doc_HinhResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] Doc_HinhResult;
        
        public Doc_HinhResponseBody() {
        }
        
        public Doc_HinhResponseBody(byte[] Doc_HinhResult) {
            this.Doc_HinhResult = Doc_HinhResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ghi_HinhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ghi_Hinh", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.Ghi_HinhRequestBody Body;
        
        public Ghi_HinhRequest() {
        }
        
        public Ghi_HinhRequest(FORM_DO_AN.ServiceReference1.Ghi_HinhRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ghi_HinhRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ma_so;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] Nhi_phan_Hinh;
        
        public Ghi_HinhRequestBody() {
        }
        
        public Ghi_HinhRequestBody(string Ma_so, byte[] Nhi_phan_Hinh) {
            this.Ma_so = Ma_so;
            this.Nhi_phan_Hinh = Nhi_phan_Hinh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ghi_HinhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ghi_HinhResponse", Namespace="http://tempuri.org/", Order=0)]
        public FORM_DO_AN.ServiceReference1.Ghi_HinhResponseBody Body;
        
        public Ghi_HinhResponse() {
        }
        
        public Ghi_HinhResponse(FORM_DO_AN.ServiceReference1.Ghi_HinhResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ghi_HinhResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ghi_HinhResult;
        
        public Ghi_HinhResponseBody() {
        }
        
        public Ghi_HinhResponseBody(string Ghi_HinhResult) {
            this.Ghi_HinhResult = Ghi_HinhResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XL_DICH_VU_ASMXSoapChannel : FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XL_DICH_VU_ASMXSoapClient : System.ServiceModel.ClientBase<FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap>, FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap {
        
        public XL_DICH_VU_ASMXSoapClient() {
        }
        
        public XL_DICH_VU_ASMXSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XL_DICH_VU_ASMXSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XL_DICH_VU_ASMXSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XL_DICH_VU_ASMXSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FORM_DO_AN.ServiceReference1.docDuLieuResponse FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.docDuLieu(FORM_DO_AN.ServiceReference1.docDuLieuRequest request) {
            return base.Channel.docDuLieu(request);
        }
        
        public string docDuLieu() {
            FORM_DO_AN.ServiceReference1.docDuLieuRequest inValue = new FORM_DO_AN.ServiceReference1.docDuLieuRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.docDuLieuRequestBody();
            FORM_DO_AN.ServiceReference1.docDuLieuResponse retVal = ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).docDuLieu(inValue);
            return retVal.Body.docDuLieuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.docDuLieuResponse> FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.docDuLieuAsync(FORM_DO_AN.ServiceReference1.docDuLieuRequest request) {
            return base.Channel.docDuLieuAsync(request);
        }
        
        public System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.docDuLieuResponse> docDuLieuAsync() {
            FORM_DO_AN.ServiceReference1.docDuLieuRequest inValue = new FORM_DO_AN.ServiceReference1.docDuLieuRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.docDuLieuRequestBody();
            return ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).docDuLieuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FORM_DO_AN.ServiceReference1.docBangResponse FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.docBang(FORM_DO_AN.ServiceReference1.docBangRequest request) {
            return base.Channel.docBang(request);
        }
        
        public string docBang(string tenBang, string cot, string dieuKien) {
            FORM_DO_AN.ServiceReference1.docBangRequest inValue = new FORM_DO_AN.ServiceReference1.docBangRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.docBangRequestBody();
            inValue.Body.tenBang = tenBang;
            inValue.Body.cot = cot;
            inValue.Body.dieuKien = dieuKien;
            FORM_DO_AN.ServiceReference1.docBangResponse retVal = ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).docBang(inValue);
            return retVal.Body.docBangResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.docBangResponse> FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.docBangAsync(FORM_DO_AN.ServiceReference1.docBangRequest request) {
            return base.Channel.docBangAsync(request);
        }
        
        public System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.docBangResponse> docBangAsync(string tenBang, string cot, string dieuKien) {
            FORM_DO_AN.ServiceReference1.docBangRequest inValue = new FORM_DO_AN.ServiceReference1.docBangRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.docBangRequestBody();
            inValue.Body.tenBang = tenBang;
            inValue.Body.cot = cot;
            inValue.Body.dieuKien = dieuKien;
            return ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).docBangAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FORM_DO_AN.ServiceReference1.themDuLieuResponse FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.themDuLieu(FORM_DO_AN.ServiceReference1.themDuLieuRequest request) {
            return base.Channel.themDuLieu(request);
        }
        
        public string themDuLieu(string chuoiXml) {
            FORM_DO_AN.ServiceReference1.themDuLieuRequest inValue = new FORM_DO_AN.ServiceReference1.themDuLieuRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.themDuLieuRequestBody();
            inValue.Body.chuoiXml = chuoiXml;
            FORM_DO_AN.ServiceReference1.themDuLieuResponse retVal = ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).themDuLieu(inValue);
            return retVal.Body.themDuLieuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.themDuLieuResponse> FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.themDuLieuAsync(FORM_DO_AN.ServiceReference1.themDuLieuRequest request) {
            return base.Channel.themDuLieuAsync(request);
        }
        
        public System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.themDuLieuResponse> themDuLieuAsync(string chuoiXml) {
            FORM_DO_AN.ServiceReference1.themDuLieuRequest inValue = new FORM_DO_AN.ServiceReference1.themDuLieuRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.themDuLieuRequestBody();
            inValue.Body.chuoiXml = chuoiXml;
            return ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).themDuLieuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FORM_DO_AN.ServiceReference1.Cap_nhatResponse FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.Cap_nhat(FORM_DO_AN.ServiceReference1.Cap_nhatRequest request) {
            return base.Channel.Cap_nhat(request);
        }
        
        public string Cap_nhat(string Chuoi_Xml) {
            FORM_DO_AN.ServiceReference1.Cap_nhatRequest inValue = new FORM_DO_AN.ServiceReference1.Cap_nhatRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.Cap_nhatRequestBody();
            inValue.Body.Chuoi_Xml = Chuoi_Xml;
            FORM_DO_AN.ServiceReference1.Cap_nhatResponse retVal = ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).Cap_nhat(inValue);
            return retVal.Body.Cap_nhatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.Cap_nhatResponse> FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.Cap_nhatAsync(FORM_DO_AN.ServiceReference1.Cap_nhatRequest request) {
            return base.Channel.Cap_nhatAsync(request);
        }
        
        public System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.Cap_nhatResponse> Cap_nhatAsync(string Chuoi_Xml) {
            FORM_DO_AN.ServiceReference1.Cap_nhatRequest inValue = new FORM_DO_AN.ServiceReference1.Cap_nhatRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.Cap_nhatRequestBody();
            inValue.Body.Chuoi_Xml = Chuoi_Xml;
            return ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).Cap_nhatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FORM_DO_AN.ServiceReference1.XoaResponse FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.Xoa(FORM_DO_AN.ServiceReference1.XoaRequest request) {
            return base.Channel.Xoa(request);
        }
        
        public string Xoa(string Chuoi_Xml) {
            FORM_DO_AN.ServiceReference1.XoaRequest inValue = new FORM_DO_AN.ServiceReference1.XoaRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.XoaRequestBody();
            inValue.Body.Chuoi_Xml = Chuoi_Xml;
            FORM_DO_AN.ServiceReference1.XoaResponse retVal = ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).Xoa(inValue);
            return retVal.Body.XoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.XoaResponse> FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.XoaAsync(FORM_DO_AN.ServiceReference1.XoaRequest request) {
            return base.Channel.XoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.XoaResponse> XoaAsync(string Chuoi_Xml) {
            FORM_DO_AN.ServiceReference1.XoaRequest inValue = new FORM_DO_AN.ServiceReference1.XoaRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.XoaRequestBody();
            inValue.Body.Chuoi_Xml = Chuoi_Xml;
            return ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).XoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FORM_DO_AN.ServiceReference1.Doc_HinhResponse FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.Doc_Hinh(FORM_DO_AN.ServiceReference1.Doc_HinhRequest request) {
            return base.Channel.Doc_Hinh(request);
        }
        
        public byte[] Doc_Hinh(string Ma_so) {
            FORM_DO_AN.ServiceReference1.Doc_HinhRequest inValue = new FORM_DO_AN.ServiceReference1.Doc_HinhRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.Doc_HinhRequestBody();
            inValue.Body.Ma_so = Ma_so;
            FORM_DO_AN.ServiceReference1.Doc_HinhResponse retVal = ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).Doc_Hinh(inValue);
            return retVal.Body.Doc_HinhResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.Doc_HinhResponse> FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.Doc_HinhAsync(FORM_DO_AN.ServiceReference1.Doc_HinhRequest request) {
            return base.Channel.Doc_HinhAsync(request);
        }
        
        public System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.Doc_HinhResponse> Doc_HinhAsync(string Ma_so) {
            FORM_DO_AN.ServiceReference1.Doc_HinhRequest inValue = new FORM_DO_AN.ServiceReference1.Doc_HinhRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.Doc_HinhRequestBody();
            inValue.Body.Ma_so = Ma_so;
            return ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).Doc_HinhAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FORM_DO_AN.ServiceReference1.Ghi_HinhResponse FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.Ghi_Hinh(FORM_DO_AN.ServiceReference1.Ghi_HinhRequest request) {
            return base.Channel.Ghi_Hinh(request);
        }
        
        public string Ghi_Hinh(string Ma_so, byte[] Nhi_phan_Hinh) {
            FORM_DO_AN.ServiceReference1.Ghi_HinhRequest inValue = new FORM_DO_AN.ServiceReference1.Ghi_HinhRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.Ghi_HinhRequestBody();
            inValue.Body.Ma_so = Ma_so;
            inValue.Body.Nhi_phan_Hinh = Nhi_phan_Hinh;
            FORM_DO_AN.ServiceReference1.Ghi_HinhResponse retVal = ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).Ghi_Hinh(inValue);
            return retVal.Body.Ghi_HinhResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.Ghi_HinhResponse> FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap.Ghi_HinhAsync(FORM_DO_AN.ServiceReference1.Ghi_HinhRequest request) {
            return base.Channel.Ghi_HinhAsync(request);
        }
        
        public System.Threading.Tasks.Task<FORM_DO_AN.ServiceReference1.Ghi_HinhResponse> Ghi_HinhAsync(string Ma_so, byte[] Nhi_phan_Hinh) {
            FORM_DO_AN.ServiceReference1.Ghi_HinhRequest inValue = new FORM_DO_AN.ServiceReference1.Ghi_HinhRequest();
            inValue.Body = new FORM_DO_AN.ServiceReference1.Ghi_HinhRequestBody();
            inValue.Body.Ma_so = Ma_so;
            inValue.Body.Nhi_phan_Hinh = Nhi_phan_Hinh;
            return ((FORM_DO_AN.ServiceReference1.XL_DICH_VU_ASMXSoap)(this)).Ghi_HinhAsync(inValue);
        }
    }
}
